### ISSUE TITLE
Investigate the assignment

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/internships#3]
I would like you all to understand fully what we are going to achieve with this project. The main goal is to create a modern, responsive and comfortable web application for students who are looking for their interships.

What should be on website like this?
- [x] some nice landing page of course
- [x] information about mandatory interships on the university
- [x] sortable and filterable list of all companies and institutions offering an internship opportunities
- [x] map with these companies
- [ ] maybe some testimonials from graduates?
- [x] maybe some sets of required documents?
- [x] maybe something else?

I think this is a good place for discussion about your ideas.

**Comment by LukaszPodlipski** [comment]
Wstępna wizualizacja strony. Zakładki: Home, Informacje o praktykach, Regulamin praktyk, Pliki do pobrania. 

![image](https://user-images.githubusercontent.com/73656796/124278662-d143b080-db46-11eb-8c17-a650fb85e1dd.png)

**Comment by plencka** [comment]
Page should be easy to navigate and transparent to the user. Some form of quick access menu could help us figure out, which subpages are necessary for this web application. I personally wouldn't hide every "information" under one subtitle. If I want to find out when deadline is, I'd expect to locate info under "Timetables" category. Same for documents, internship statute, mentors, etc.. I'd prefer to avoid situation, where user needs to click through whole menu to find their desired information.

Sortable and filterable list is a neat idea. Somebody enjoying graphic design might not want to search through programming companies. We could also implement a button to export filtered results to file for further processing.

I don't enjoy the idea of testimonials. Ideal solution would be giving users ability to comment on companies, but it's not plausible to implement without a database. Static information of this type would require additional cooperation between webpage owner and students. Additionally, linking company data with testimonials might introduce complexity to the project if we wanted to keep those files separate for easier editing. Otherwise, company files with descriptions and opinions might get quite large.
Though I'm open to it if there's creative solution to these issues.

**Comment by brzozka** [comment]
In addition hovering over, or clicking on a map pointer should show more info about the company for example their website, maybe some short description, exact address, company logo, some form of contact.

**Comment by LukaszPodlipski** [comment]
I agree with my teammates
